### ISSUE TITLE
Add uuid and guid to command line script

### ISSUE THREAD

**Issue by FranceCosta** [nerve-bio/NERVE#35]

**Comment by FranceCosta** [comment]
I have added them in NERVE.sh as follows:
```
...
docker run --network nerve-network -p 8880:8880 -it -u $(id -u):$(id -g) -v $(pwd)/:/workdir nerve:$NERVE_VERSION "$@"
```

and got the following error:
```
 ./NERVE.sh -epp False -vir True -rz True -p1 UP000000625 -g n -m True -wd ./ecoli
Traceback (most recent call last):
  File "/usr/nerve_python/NERVE/code/NERVE.py", line 20, in <module>
    from code.Epitope import epitope
  File "/workdir/code/Epitope.py", line 4, in <module>
    from epitopepredict import base, plotting
  File "/usr/local/lib/python3.8/site-packages/epitopepredict/__init__.py", line 1, in <module>
    from .base import *
  File "/usr/local/lib/python3.8/site-packages/epitopepredict/base.py", line 45, in <module>
    config_file = config.write_default_config()
  File "/usr/local/lib/python3.8/site-packages/epitopepredict/config.py", line 66, in write_default_config
    os.makedirs(config_path, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.config'
```
